"""Render Python-typed :class:`Function` objects into ``.pyi`` text."""
from __future__ import annotations

import re

from .model import Function

_HEADER = '''\
"""Type stub for the native ``_vanillapdf`` C extension.

AUTO-GENERATED by ``scripts/generate_native_stub.py`` from the native
``PyMethodDef`` tables + capsule/handle analysis. Do not edit by hand; re-run
the generator (and hand-correct here only if a heuristic misfires).

Handles are opaque, named PyCapsules. The binding validates the capsule name at
every boundary (``capsule_cast``/``object_cast``), so passing the wrong handle
raises ``TypeError``/``PdfError`` at runtime rather than reaching the native
``reinterpret_cast``. Giving each native handle type a distinct marker class here
(carried by the wrappers via ``Handle[<X>Handle]``) moves that check to pyright:
a wrong handle is caught in the editor/CI instead of at runtime. All syntax
objects share the ``ObjectHandle`` capsule (converted via ``object_cast``, which
validates the object type and raises on mismatch).
"""
from typing import final
'''

_HANDLE_DOC = '    """Opaque native handle (a PyCapsule). Not constructible from Python."""'


def _handle_types(functions: list[Function]) -> list[str]:
    """Every distinct ``*Handle`` marker type referenced by the signatures."""
    names: set[str] = set()
    for fn in functions:
        for token in re.findall(r"\b(\w+Handle)\b", fn.return_type):
            names.add(token)
        for param in fn.params:
            names.update(re.findall(r"\b(\w+Handle)\b", param.annotation))
    return sorted(names)


def render(functions: list[Function]) -> str:
    """Return the full ``.pyi`` text for the given signatures."""
    lines = [_HEADER]
    for handle in _handle_types(functions):
        lines.append(f"\n\n@final\nclass {handle}:")
        lines.append(_HANDLE_DOC)
    lines.append("\n\nclass PdfError(Exception):")
    lines.append('    """Raised when a native operation fails; carries the numeric error code."""')
    lines.append("    error_code: int")
    lines.append("")
    for fn in functions:
        lines.append(f"\n{fn.render()}")
    return "\n".join(lines) + "\n"
